[project]
name = 'Rare-Disease-Research-DARDR-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.data-sharing]
path = 'contracts/data-sharing.clar'
clarity_version = 2
epoch = 2.5

[contracts.patient-incentives]
path = 'contracts/patient-incentives.clar'
clarity_version = 2
epoch = 2.5

[contracts.research-proposals]
path = 'contracts/research-proposals.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
